name: Changelog
on:
  pull_request:
    types: [opened, synchronize]
    branches: [master]
    paths: 
      - "BlobViaEventGrid/*"
      - "DiagnosticData/*"
      - "EventHub/*"
      - "StorageQueue/*"
      - "BlobToOtel/*"

jobs:   
  check-changelog-updates:
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'skip changelog') }}
    runs-on: ubuntu-latest
    name: Check Changelog Updates
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c

    - name: Check changelog file 
      run: |
        changed_files_string="${{ steps.changed-files.outputs.all_changed_files }}"
        read -ra changed_files_array <<< "$changed_files_string"
        chmod +x scripts/changelog_check.sh
        for changed_file in "${changed_files_array[@]}"; do
          if [[ "$changed_file" == "BlobViaEventGrid/"* ]] || [[ "$changed_file" == "DiagnosticData/"* ]] || [[ "$changed_file" == "EventHub/"* ]] || [[ "$changed_file" == "StorageQueue/"* ]] || [[ "$changed_file" == "BlobToOtel/"* ]]; then
            scripts/changelog_check.sh  $(echo "$changed_file)" | cut -d "/" -f1)
          fi
        done
