name: Changelog
on:
  pull_request:
    types: [opened, synchronize]
    branches: [master]
    paths: 
      - "BlobViaEventGrid/*"
      - "DiagnosticData/*"
      - "EventHub/*"
      - "StorageQueue/*"
      - "BlobToOtel/*"

jobs:   
  check-changelog-updates:
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'skip changelog') }}
    runs-on: ubuntu-latest
    name: Check changelog update
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c
      with:
        files: |
          **/CHANGELOG.md

    - name: Check changelog file 
      run: |
        if [[ "${{ steps.changed-files.outputs.all_changed_files }}" = "" ]]; then
          echo "Please add a changelog entry in CHANGELOG.md or add 'skip changelog' label to your PR if this change does not require an entry".
          exit 1
        fi